on: push
name: run tests
jobs:
  test-and-lint:
    name: testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: npm install
        uses: actions/setup-node@v1
      - run: npm install
      - run: npm test test_api.js
    
